name: Waka Readme

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_TITLE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_TOTAL: "True"
          SHOW_PROFILE_VIEWS: "False"
          COMMIT_BY_ME: "True"
          SHOW_TIME: "False"
          COMMIT_MESSAGE: "WakaTime Workflow AutoCommiter"
          
